name: Deploy to DigitalOcean
on:
  push:
    branches:
      - "*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}

      - name: Copy code to droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          port: ${{ secrets.DIGITALOCEAN_SSH_PORT }}
          source: "."
          target: "/home/${{ secrets.DIGITALOCEAN_USERNAME }}/ArtyAgency"

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker.io docker-compose

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          port: ${{ secrets.DIGITALOCEAN_SSH_PORT }}
          script: |
            cd /home/${{ secrets.DIGITALOCEAN_USERNAME }}/ArtyAgency
            docker-compose pull
            docker-compose up -d
